# Основы работы с numpy

In [1]:
import numpy as np

## Тензоры 0-го ранга

In [3]:
a = np.array(10)
a

array(10)

In [5]:
a.ndim

0

In [6]:
a.shape

()

## Тензоры 1-го ранга

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [13]:
a.ndim

1

In [14]:
a.shape

(5,)

In [15]:
# Обращение к элементу
a[2]

3

In [17]:
# Cрез c 1 по 4 элементы
a[1:4]

array([2, 3, 4])

In [11]:
a[2:-1]

array([3, 4])

## Тензоры 2-го ранга

In [30]:
a = np.array([[1, 2, 13, 14],
              [5, 6, 17, 18],
              [9, 3, 11, 12]])
a

array([[ 1,  2, 13, 14],
       [ 5,  6, 17, 18],
       [ 9,  3, 11, 12]])

In [31]:
a.ndim

2

In [32]:
a.shape

(3, 4)

In [33]:
# Обращение к элементу
a[2, 1]

3

In [34]:
# Извлечение строки под номером 1
a[1]

array([ 5,  6, 17, 18])

In [35]:
# Извлечение строки под номером 1,
# явно задав выбор всех элементов столбца
a[1, :]

array([ 5,  6, 17, 18])

In [36]:
# Извлечение столбца под номером 2
a[:, 2]

array([13, 17, 11])

In [39]:
# Извлечение элементов, лежащих на строке 1 и
# на столбцах от номера 1 до номера 3.
# Получаются срединные элементы
a[1, 1:3]

array([ 6, 17])

## Тензоры 3-го ранга

In [12]:
a = np.array([[[10, 11, 12],
               [14, 15, 16],
               [18, 19, 20]],
              [[22, 23, 24],
               [26, 27, 28],
               [30, 31, 32]],
              [[34, 35, 36],
               [38, 39, 40],
               [42, 43, 44]]])
a

array([[[10, 11, 12],
        [14, 15, 16],
        [18, 19, 20]],

       [[22, 23, 24],
        [26, 27, 28],
        [30, 31, 32]],

       [[34, 35, 36],
        [38, 39, 40],
        [42, 43, 44]]])

In [13]:
a.ndim

3

In [14]:
a.shape

(3, 3, 3)

In [16]:
# Извлечение элемента матрицы под номером 1,
# строке под номером 2,
# столбце под номером 3
a[1][2][0]

30

In [18]:
# Аналогично через запятые
a[1,2,0]

30

In [19]:
# Извлечение матрицы под номером 2
a[2]

array([[34, 35, 36],
       [38, 39, 40],
       [42, 43, 44]])

In [20]:
# Извлечение у матрицы под номером 2
# строки под номером 1
a[2, 1] 

array([38, 39, 40])

In [21]:
# Извлечение у матрицы нод номером 0
# столбец под номером 2
a[0, :, 2]

array([12, 16, 20])

In [22]:
# Извлечение у каждой из матриц элемента, стоящего
# на строке под номером 1 и
# столбце под номером 1
a[:, 1, 0]

array([14, 26, 38])